syntax = "proto3";

import "com/eblan/launcher/data/datastore/proto/model/grid_item_settings.proto";
import "com/eblan/launcher/data/datastore/proto/appdrawer/app_drawer_type.proto";
import "com/eblan/launcher/data/datastore/proto/model/background_color.proto";
import "com/eblan/launcher/data/datastore/proto/appdrawer/search_bar_position.proto";
import "com/eblan/launcher/data/datastore/proto/appdrawer/scroll_bar_type.proto";

option java_package = "com.eblan.launcher.data.datastore.proto.appdrawer";
option java_multiple_files = true;

message AppDrawerSettingsProto {
  optional int32 appDrawerColumns = 1;
  optional int32 appDrawerRowsHeight = 2;
  GridItemSettingsProto gridItemSettingsProto = 3;
  optional BackgroundColorProto backgroundColorProto = 5;
  optional int32 customBackgroundColor = 6;
  optional AppDrawerTypeProto AppDrawerTypeProto = 8;
  optional int32 horizontalAppDrawerColumns = 9;
  optional int32 horizontalAppDrawerRows = 10;
  optional bool excludeTaggedApps = 11;
  optional bool showKeyboard = 12;
  optional bool fuzzySearch = 13;
  optional bool blurBehind = 14;
  optional SearchBarPositionProto searchBarPositionProto = 15;
  optional ScrollBarTypeProto scrollBarTypeProto = 16;
}