syntax = "proto3";

import "com/eblan/launcher/data/datastore/proto/general/theme.proto";
import "com/eblan/launcher/data/datastore/proto/general/icon_color.proto";

option java_package = "com.eblan.launcher.data.datastore.proto.general";
option java_multiple_files = true;

message GeneralSettingsProto {
  optional ThemeProto themeProto = 1;
  optional bool dynamicTheme = 3;
  optional string iconPackInfoPackageName = 4;
  optional IconColorProto iconColorProto = 5;
  optional int32 customIconColor = 6;
  optional bool fallbackIconColor = 7;
}