syntax = "proto3";

import "com/eblan/launcher/data/datastore/proto/model/grid_item_settings.proto";

option java_package = "com.eblan.launcher.data.datastore.proto.home";
option java_multiple_files = true;

message HomeSettingsProto {
  optional int32 columns = 1;
  optional int32 rows = 2;
  optional int32 pageCount = 3;
  optional bool infiniteScroll = 4;
  optional int32 dockColumns = 5;
  optional int32 dockRows = 6;
  optional int32 dockHeight = 7;
  optional int32 initialPage = 8;
  optional bool wallpaperScroll = 9;
  GridItemSettingsProto gridItemSettingsProto = 12;
  optional bool lockScreenOrientation = 13;
  optional int32 dockPageCount = 14;
  optional bool dockInfiniteScroll = 15;
  optional int32 dockInitialPage = 16;
  optional bool addNewAppsToHomeScreen = 17;
  optional bool showPageIndicator = 22;
  optional int32 dockCustomBackgroundColor = 23;
  optional int32 dockPadding = 24;
  optional int32 dockTopStartCornerRadius = 25;
  optional int32 dockTopEndCornerRadius = 26;
  optional int32 dockBottomStartCornerRadius = 27;
  optional int32 dockBottomEndCornerRadius = 28;
}