syntax = "proto3";

import "com/eblan/launcher/data/datastore/proto/model/grid_item_settings.proto";

option java_package = "com.eblan.launcher.data.datastore.proto.home";
option java_multiple_files = true;

message HomeSettingsProto {
  int32 columns = 1;
  int32 rows = 2;
  int32 pageCount = 3;
  bool infiniteScroll = 4;
  int32 dockColumns = 5;
  int32 dockRows = 6;
  int32 dockHeight = 7;
  int32 initialPage = 8;
  bool wallpaperScroll = 9;
  GridItemSettingsProto gridItemSettingsProto = 12;
  bool lockScreenOrientation = 13;
  int32 dockPageCount = 14;
  bool dockInfiniteScroll = 15;
  int32 dockInitialPage = 16;
  bool addNewAppsToHomeScreen = 17;
  bool showPageIndicator = 22;
  int32 dockCustomBackgroundColor = 23;
  int32 dockPadding = 24;
  int32 dockTopStartCornerRadius = 25;
  int32 dockTopEndCornerRadius = 26;
  int32 dockBottomStartCornerRadius = 27;
  int32 dockBottomEndCornerRadius = 28;
}